# Generated by Django 3.0.5 on 2020-04-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200406_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(default='http://localhost:8000/static/mainapp/img/bg-img/10.jpg', max_length=1000),
        ),
    ]
